import { Career } from "./types";

export const PREGRADO_CAREERS: Career[] = [
  // ==========================================
  // PREGRADO QUITO (UIO) — 21 CARRERAS
  // ==========================================
  {
    id: "uio-administracion-empresas",
    name: "Administración de Empresas",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-administracion-de-empresas/",
    faculty: "Business & Management School",
    semesters: 8,
    credits: 160,
    matriculaSem: 335.0,
    colegiaturaSem: 3359.82,
    costoTotalSem: 3694.82,
    totalTuitionRef: 29558.56,
    totalConBeca: 23914.08,
    ahorroBeca: 5644.48,
    asuDualDegree: true,
    asuPathway: "W. P. Carey School of Business #1 en Innovación USA",
    iconName: "Briefcase",
    description: "Formación directiva de vanguardia con visión global, simulación de negocios e inmersión gerencial.",
    highlight: "Doble titulación ASU W. P. Carey School of Business"
  },
  {
    id: "uio-arquitectura",
    name: "Arquitectura",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-arquitectura/",
    faculty: "Facultad de Arquitectura, Diseño y Arte",
    semesters: 10,
    credits: 200,
    matriculaSem: 335.0,
    colegiaturaSem: 3357.15,
    costoTotalSem: 3692.15,
    totalTuitionRef: 36921.5,
    totalConBeca: 29871.5,
    ahorroBeca: 7050.0,
    asuDualDegree: true,
    asuPathway: "Herberger Institute for Design and the Arts ASU",
    iconName: "Building2",
    description: "Diseño bioclimático, urbanismo sustentable y modelado paramétrico BIM.",
    highlight: "Enfoque Bioclimático & Certificación Sostenible ASU"
  },
  {
    id: "uio-ciencias-politicas",
    name: "Ciencias Políticas y Relaciones Internacionales",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-ciencias-politicas-y-relaciones-internacionales/",
    faculty: "Facultad de Jurisprudencia y Ciencias Sociales",
    semesters: 8,
    credits: 160,
    matriculaSem: 333.5,
    colegiaturaSem: 3335.5,
    costoTotalSem: 3669.0,
    totalTuitionRef: 29352.0,
    totalConBeca: 23748.4,
    ahorroBeca: 5603.6,
    asuDualDegree: true,
    asuPathway: "The College of Liberal Arts and Sciences ASU",
    iconName: "Globe",
    description: "Diplomacia global, gobernanza democrática y análisis geopolítico estratégico.",
    highlight: "Programa 3+1 con Arizona State University"
  },
  {
    id: "uio-comunicacion-medios",
    name: "Comunicación y Medios Digitales",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-comunicacion-y-medios-digitales/",
    faculty: "Escuela de Comunicación y Contenidos Digitales",
    semesters: 8,
    credits: 160,
    matriculaSem: 310.0,
    colegiaturaSem: 3110.31,
    costoTotalSem: 3420.31,
    totalTuitionRef: 27362.48,
    totalConBeca: 22137.12,
    ahorroBeca: 5225.36,
    asuDualDegree: true,
    asuPathway: "Walter Cronkite School of Journalism and Mass Communication ASU",
    iconName: "Radio",
    description: "Narrativas transmedia, creación de contenidos inmersivos y periodismo digital.",
    highlight: "Alianza con Walter Cronkite School of Journalism ASU"
  },
  {
    id: "uio-derecho",
    name: "Derecho",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-derecho/",
    faculty: "Facultad de Jurisprudencia y Ciencias Sociales",
    semesters: 8,
    credits: 160,
    matriculaSem: 310.0,
    colegiaturaSem: 3110.31,
    costoTotalSem: 3420.31,
    totalTuitionRef: 27362.48,
    totalConBeca: 22137.12,
    ahorroBeca: 5225.36,
    asuDualDegree: true,
    asuPathway: "Sandra Day O'Connor College of Law ASU",
    iconName: "Scale",
    description: "Litigio oral, derecho corporativo, justicia digital y arbitraje internacional.",
    highlight: "Clínica Jurídica y Litigio Estratégico Internacional"
  },
  {
    id: "uio-diseno-grafico",
    name: "Diseño Gráfico",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-diseno-grafico/",
    faculty: "Facultad de Arquitectura, Diseño y Arte",
    semesters: 8,
    credits: 160,
    matriculaSem: 338.0,
    colegiaturaSem: 3385.8,
    costoTotalSem: 3723.8,
    totalTuitionRef: 29790.4,
    totalConBeca: 24102.24,
    ahorroBeca: 5688.16,
    asuDualDegree: true,
    asuPathway: "Herberger Institute for Design and the Arts ASU",
    iconName: "Palette",
    description: "Identidad visual, diseño UI/UX, animación digital y dirección de arte publicitaria.",
    highlight: "Talleres experimentales y certificación Adobe & ASU"
  },
  {
    id: "uio-enfermeria",
    name: "Enfermería",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-enfermeria/",
    faculty: "Facultad de Ciencias Médicas y de la Salud",
    semesters: 8,
    credits: 160,
    matriculaSem: 229.0,
    colegiaturaSem: 2295.98,
    costoTotalSem: 2524.98,
    totalTuitionRef: 20199.84,
    totalConBeca: 16342.56,
    ahorroBeca: 3857.28,
    asuDualDegree: true,
    asuPathway: "Edson College of Nursing and Health Innovation ASU",
    iconName: "Activity",
    description: "Cuidado clínico de alta complejidad, simulación médica y salud comunitaria.",
    highlight: "Centro de simulación médica avanzada con estándares internacionales"
  },
  {
    id: "uio-finanzas-negocios-digitales",
    name: "Finanzas y Negocios Digitales",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-finanzas-y-negocios-digitales/",
    faculty: "Business & Management School",
    semesters: 8,
    credits: 160,
    matriculaSem: 335.0,
    colegiaturaSem: 3359.82,
    costoTotalSem: 3694.82,
    totalTuitionRef: 29558.56,
    totalConBeca: 23914.08,
    ahorroBeca: 5644.48,
    asuDualDegree: true,
    asuPathway: "W. P. Carey School of Business ASU",
    iconName: "Coins",
    description: "Mercados bursátiles, finanzas cuantitativas, Fintech y análisis con Big Data.",
    highlight: "Laboratorio Financiero Bloomberg y vinculación Diners Club"
  },
  {
    id: "uio-fisioterapia",
    name: "Fisioterapia",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-fisioterapia/",
    faculty: "Facultad de Ciencias Médicas y de la Salud",
    semesters: 8,
    credits: 160,
    matriculaSem: 327.0,
    colegiaturaSem: 3278.66,
    costoTotalSem: 3605.66,
    totalTuitionRef: 28845.28,
    totalConBeca: 23337.12,
    ahorroBeca: 5508.16,
    asuDualDegree: true,
    asuPathway: "College of Health Solutions ASU",
    iconName: "HeartPulse",
    description: "Rehabilitación osteomuscular, fisioterapia deportiva y tecnología biomecánica.",
    highlight: "Clínica de Rehabilitación y convenios con federaciones deportivas"
  },
  {
    id: "uio-gastronomia",
    name: "Gastronomía",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-gastronomia/",
    faculty: "Escuela de Hospitalidad y Arte Culinario",
    semesters: 8,
    credits: 160,
    matriculaSem: 339.0,
    colegiaturaSem: 3404.87,
    costoTotalSem: 3743.87,
    totalTuitionRef: 29950.96,
    totalConBeca: 24230.28,
    ahorroBeca: 5720.68,
    asuDualDegree: false,
    asuPathway: "Culinary Arts & Food Innovation Track",
    iconName: "UtensilsCrossed",
    description: "Técnicas culinarias de autor, gestión de restaurantes e innovación agroalimentaria.",
    highlight: "Cocinas de estándar internacional y pasantías en restaurantes Estrella Michelin"
  },
  {
    id: "uio-ingenieria-automotriz",
    name: "Ingeniería Automotriz",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-ingenieria-automotriz/",
    faculty: "Facultad de Ciencias Técnicas e Ingenierías",
    semesters: 8,
    credits: 160,
    matriculaSem: 312.0,
    colegiaturaSem: 3119.55,
    costoTotalSem: 3431.55,
    totalTuitionRef: 27452.4,
    totalConBeca: 22208.99,
    ahorroBeca: 5243.41,
    asuDualDegree: true,
    asuPathway: "Ira A. Fulton Schools of Engineering ASU",
    iconName: "Car",
    description: "Electromovilidad, vehículos híbridos/autónomos y dinámica vehicular computacional.",
    highlight: "Autódromo y pistas de prueba propios en el Campus UIDE Quito"
  },
  {
    id: "uio-ingenieria-civil",
    name: "Ingeniería Civil",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-ingenieria-civil/",
    faculty: "Facultad de Ciencias Técnicas e Ingenierías",
    semesters: 8,
    credits: 160,
    matriculaSem: 327.0,
    colegiaturaSem: 3278.66,
    costoTotalSem: 3605.66,
    totalTuitionRef: 28845.28,
    totalConBeca: 23337.12,
    ahorroBeca: 5508.16,
    asuDualDegree: true,
    asuPathway: "Ira A. Fulton Schools of Engineering ASU",
    iconName: "HardHat",
    description: "Cálculo sismorresistente, infraestructura vial, geotecnia y gerencia de megaproyectos.",
    highlight: "Laboratorio de estructuras sismo-resistentes y geotecnia avanzada"
  },
  {
    id: "uio-ingenieria-sistemas",
    name: "Ingeniería en Sistemas de la Información",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-ingenieria-en-sistemas-de-la-informacion/",
    faculty: "Escuela de Tecnologías de la Información",
    semesters: 8,
    credits: 160,
    matriculaSem: 312.0,
    colegiaturaSem: 3118.54,
    costoTotalSem: 3430.54,
    totalTuitionRef: 27444.32,
    totalConBeca: 22202.45,
    ahorroBeca: 5241.87,
    asuDualDegree: true,
    asuPathway: "Ira A. Fulton Schools of Engineering ASU",
    iconName: "Laptop",
    description: "Arquitectura Cloud, ciberseguridad, DevOps, ingeniería de datos y sistemas distribuidos.",
    highlight: "Curriculum alineado a Ira A. Fulton Schools of Engineering ASU"
  },
  {
    id: "uio-ingenieria-industrial",
    name: "Ingeniería Industrial",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-ingenieria-industrial/",
    faculty: "Facultad de Ciencias Técnicas e Ingenierías",
    semesters: 8,
    credits: 160,
    matriculaSem: 250.0,
    colegiaturaSem: 2499.58,
    costoTotalSem: 2749.58,
    totalTuitionRef: 21996.64,
    totalConBeca: 17795.28,
    ahorroBeca: 4201.36,
    asuDualDegree: true,
    asuPathway: "Ira A. Fulton Schools of Engineering ASU",
    iconName: "Factory",
    description: "Optimización de procesos, cadena de suministro, lean manufacturing y analítica de operaciones.",
    highlight: "Certificación Green Belt Six Sigma integrada"
  },
  {
    id: "uio-ingenieria-mecatronica",
    name: "Ingeniería Mecatrónica",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-ingenieria-mecatronica/",
    faculty: "Facultad de Ciencias Técnicas e Ingenierías",
    semesters: 8,
    credits: 160,
    matriculaSem: 335.0,
    colegiaturaSem: 3355.32,
    costoTotalSem: 3690.32,
    totalTuitionRef: 29522.56,
    totalConBeca: 23885.6,
    ahorroBeca: 5636.96,
    asuDualDegree: true,
    asuPathway: "Ira A. Fulton Schools of Engineering ASU",
    iconName: "Cpu",
    description: "Robótica industrial, sensórica IoT, automatización y gemelos digitales para la Industria 4.0.",
    highlight: "Laboratorio de manufactura avanzada y robótica colaborativa"
  },
  {
    id: "uio-medicina-veterinaria",
    name: "Medicina Veterinaria",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-medicina-veterinaria/",
    faculty: "Facultad de Ciencias Médicas y de la Salud",
    semesters: 10,
    credits: 200,
    matriculaSem: 383.0,
    colegiaturaSem: 3836.97,
    costoTotalSem: 4219.97,
    totalTuitionRef: 42199.7,
    totalConBeca: 34142.16,
    ahorroBeca: 8057.54,
    asuDualDegree: true,
    asuPathway: "College of Integrative Sciences and Arts ASU",
    iconName: "Bone",
    description: "Medicina de pequeñas y grandes especies, cirugía veterinaria, epidemiología y bioseguridad.",
    highlight: "Hospital Veterinario Docente propio en campus Quito"
  },
  {
    id: "uio-multimedia-produccion",
    name: "Multimedia y Producción Audiovisual",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-multimedia-y-produccion-audiovisual/",
    faculty: "Escuela de Comunicación y Contenidos Digitales",
    semesters: 8,
    credits: 160,
    matriculaSem: 336.0,
    colegiaturaSem: 3363.83,
    costoTotalSem: 3699.83,
    totalTuitionRef: 29598.64,
    totalConBeca: 23945.3,
    ahorroBeca: 5653.34,
    asuDualDegree: true,
    asuPathway: "Sidney Poitier New American Film School ASU",
    iconName: "Clapperboard",
    description: "Cinematografía digital, efectos visuales VFX, postproducción y sonido envolvente.",
    highlight: "Estudios de televisión 4K y salas de mezcla de audio profesional"
  },
  {
    id: "uio-negocios-internacionales",
    name: "Negocios Internacionales",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-negocios-internacionales/",
    faculty: "Business & Management School",
    semesters: 8,
    credits: 160,
    matriculaSem: 335.0,
    colegiaturaSem: 3359.82,
    costoTotalSem: 3694.82,
    totalTuitionRef: 29558.56,
    totalConBeca: 23914.08,
    ahorroBeca: 5644.48,
    asuDualDegree: true,
    asuPathway: "Thunderbird School of Global Management ASU",
    iconName: "Briefcase",
    description: "Comercio internacional, logística de puertos, tratados de libre comercio y diplomacia corporativa.",
    highlight: "Doble titulación ASU Thunderbird #1 en Gestión Global"
  },
  {
    id: "uio-nutricion-dietetica",
    name: "Nutrición y Dietética",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-nutricion-y-dietetica/",
    faculty: "Facultad de Ciencias Médicas y de la Salud",
    semesters: 10,
    credits: 200,
    matriculaSem: 344.0,
    colegiaturaSem: 3445.2,
    costoTotalSem: 3789.2,
    totalTuitionRef: 37892.0,
    totalConBeca: 30654.92,
    ahorroBeca: 7237.08,
    asuDualDegree: true,
    asuPathway: "College of Health Solutions ASU",
    iconName: "Apple",
    description: "Nutrición clínica hospitalaria, dietética comunitaria y rendimiento deportivo de alta competencia.",
    highlight: "Laboratorios de bromatología y consulta nutricional docente"
  },
  {
    id: "uio-odontologia",
    name: "Odontología",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-odontologia/",
    faculty: "Facultad de Ciencias Médicas y de la Salud",
    semesters: 10,
    credits: 200,
    matriculaSem: 377.0,
    colegiaturaSem: 3772.23,
    costoTotalSem: 4149.23,
    totalTuitionRef: 41492.3,
    totalConBeca: 33568.76,
    ahorroBeca: 7923.54,
    asuDualDegree: true,
    asuPathway: "Pre-Dental Track & Health Sciences ASU",
    iconName: "Smile",
    description: "Cirugía maxilofacial, rehabilitación oral digital, periodoncia y endodoncia microscópica.",
    highlight: "Clínicas Odontológicas UIDE con sillones dentales de última generación"
  },
  {
    id: "uio-psicologia-clinica",
    name: "Psicología Clínica",
    campus: "Quito",
    url: "https://www.uide.edu.ec/carreras-quito/carrera-de-psicologia-clinica/",
    faculty: "Facultad de Jurisprudencia y Ciencias Sociales",
    semesters: 8,
    credits: 160,
    matriculaSem: 362.0,
    colegiaturaSem: 3618.77,
    costoTotalSem: 3980.77,
    totalTuitionRef: 31846.16,
    totalConBeca: 25763.54,
    ahorroBeca: 6082.62,
    asuDualDegree: true,
    asuPathway: "Department of Psychology ASU",
    iconName: "Brain",
    description: "Psicodiagnóstico avanzado, neuropsicología, psicoterapia basada en evidencia y salud mental.",
    highlight: "Cámara Gesell propia y centro de atención psicológica comunitaria"
  },

  // ==========================================
  // PREGRADO GUAYAQUIL — 1 CARRERA
  // ==========================================
  {
    id: "gye-comercio-exterior",
    name: "Comercio Exterior y Aduanas",
    campus: "Guayaquil",
    url: "https://www.uide.edu.ec/carreras-guayaquil/carrera-de-comercio-exterior-y-aduanas-guayaquil/",
    faculty: "Business & Management School Guayaquil",
    semesters: 8,
    credits: 160,
    matriculaSem: 180.0,
    colegiaturaSem: 1803.0,
    costoTotalSem: 1983.0,
    totalTuitionRef: 15864.0,
    totalConBeca: 12834.0,
    ahorroBeca: 3030.0,
    asuDualDegree: false,
    asuPathway: "Global Trade & Customs Track ASU",
    iconName: "Ship",
    description: "Operaciones aduaneras, comercio portuario del Pacífico, logística multimodal y regímenes arancelarios.",
    highlight: "Convenios con la Autoridad Portuaria de Guayaquil y cámaras de comercio"
  },

  // ==========================================
  // PREGRADO ONLINE — 2 CARRERAS
  // ==========================================
  {
    id: "onl-inteligencia-artificial",
    name: "Inteligencia Artificial en Línea",
    campus: "Online",
    url: "https://www.uide.edu.ec/carreras-online/carrera-de-inteligencia-artificial-en-linea/",
    faculty: "Escuela de Tecnologías Exponenciales Online",
    semesters: 8,
    credits: 160,
    matriculaSem: 135.0,
    colegiaturaSem: 1350.0,
    costoTotalSem: 1485.0,
    totalTuitionRef: 11880.0,
    totalConBeca: 9622.8,
    ahorroBeca: 2257.2,
    asuDualDegree: true,
    asuPathway: "Ira A. Fulton Schools of Engineering Online",
    iconName: "Sparkles",
    description: "Machine Learning, redes neuronales, visión por computador, procesamiento de lenguaje natural y ética de la IA.",
    highlight: "Primera carrera de IA en modalidad 100% online en el país con currículo ASU"
  },
  {
    id: "onl-derecho",
    name: "Derecho en Línea",
    campus: "Online",
    url: "https://www.uide.edu.ec/pregrado-en-linea/carrera-de-derecho-en-linea-duracion-malla-curricular-y-oportunidades-laborales/",
    faculty: "Facultad de Jurisprudencia y Ciencias Sociales Online",
    semesters: 8,
    credits: 160,
    matriculaSem: 120.0,
    colegiaturaSem: 1200.0,
    costoTotalSem: 1320.0,
    totalTuitionRef: 10560.0,
    totalConBeca: 8553.6,
    ahorroBeca: 2006.4,
    asuDualDegree: false,
    asuPathway: "Legal Innovation & Digital Law Track",
    iconName: "Scale",
    description: "Formación jurídica 100% virtual, derecho procesal constitucional, derecho civil y nuevas tecnologías jurídicas.",
    highlight: "Campus virtual de alta interacción y tutorías sincrónicas personalizadas"
  }
];

export const PREGRADO_QUITO = PREGRADO_CAREERS.filter((c) => c.campus === "Quito");
export const PREGRADO_GUAYAQUIL = PREGRADO_CAREERS.filter((c) => c.campus === "Guayaquil");
export const PREGRADO_ONLINE = PREGRADO_CAREERS.filter((c) => c.campus === "Online");
